services:
  - type: web
    name: freeze-frame
    env: python
    buildCommand: ""
    startCommand: python app.py
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
